CREATE SCHEMA IF NOT EXISTS notification;

CREATE TABLE notification.notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NOT NULL,
    booking_id BIGINT,
    type       VARCHAR(30)   NOT NULL,
    channel    VARCHAR(20)   NOT NULL,
    payload    VARCHAR(1000) NOT NULL,
    status     VARCHAR(20)   NOT NULL,
    sent_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ   NOT NULL,
    updated_at TIMESTAMPTZ   NOT NULL
);
CREATE INDEX idx_notification_user ON notification.notifications (user_id);
CREATE INDEX idx_notification_booking_type ON notification.notifications (booking_id, type);
