CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    phone         VARCHAR(15),
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

-- Seed the first ADMIN. Credentials: admin@moviebooking.com / Admin@12345 (BCrypt).
-- Rotate this password after first login in any real environment.
INSERT INTO users (name, email, phone, password_hash, role, created_at, updated_at)
VALUES ('System Admin',
        'admin@moviebooking.com',
        NULL,
        '$2y$10$Kjpbu1belx.a34FbJ0fKxuUmS.5Judj.5a3bxMc6MiVl5BGhbYujO',
        'ADMIN',
        now(),
        now());
