CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE catalog.cities (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    state      VARCHAR(100) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_city_name UNIQUE (name)
);

CREATE TABLE catalog.theatres (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id    BIGINT       NOT NULL REFERENCES catalog.cities (id),
    name       VARCHAR(150) NOT NULL,
    address    VARCHAR(255) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_theatre_city_name UNIQUE (city_id, name)
);

CREATE TABLE catalog.screens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theatre_id  BIGINT      NOT NULL REFERENCES catalog.theatres (id),
    name        VARCHAR(50) NOT NULL,
    total_seats INT         NOT NULL DEFAULT 0,
    is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_screen_theatre_name UNIQUE (theatre_id, name)
);

CREATE TABLE catalog.seats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id   BIGINT      NOT NULL REFERENCES catalog.screens (id),
    row_label   VARCHAR(3)  NOT NULL,
    seat_number INT         NOT NULL,
    seat_type   VARCHAR(20) NOT NULL,
    is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_seat_screen_row_number UNIQUE (screen_id, row_label, seat_number)
);
CREATE INDEX idx_seat_screen ON catalog.seats (screen_id);

CREATE TABLE catalog.movies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    language     VARCHAR(50)  NOT NULL,
    genre        VARCHAR(50)  NOT NULL,
    duration_min INT          NOT NULL,
    certificate  VARCHAR(5)   NOT NULL,
    release_date DATE         NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_movie_title ON catalog.movies (title);
