CREATE SCHEMA IF NOT EXISTS refund;

CREATE TABLE refund.refund_policies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_refund_policy_name UNIQUE (name)
);

CREATE TABLE refund.refund_rules (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id               BIGINT      NOT NULL REFERENCES refund.refund_policies (id),
    min_minutes_before_show INT         NOT NULL,
    refund_percent          INT         NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_refund_rule_policy_threshold UNIQUE (policy_id, min_minutes_before_show)
);
CREATE INDEX idx_refund_rule_policy ON refund.refund_rules (policy_id);
