CREATE SCHEMA IF NOT EXISTS show;

CREATE TABLE show.shows (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id          BIGINT       NOT NULL,
    movie_title       VARCHAR(200) NOT NULL,
    movie_language    VARCHAR(50)  NOT NULL,
    movie_certificate VARCHAR(5)   NOT NULL,
    duration_min      INT          NOT NULL,
    screen_id         BIGINT       NOT NULL,
    screen_name       VARCHAR(50)  NOT NULL,
    theatre_id        BIGINT       NOT NULL,
    theatre_name      VARCHAR(150) NOT NULL,
    city_id           BIGINT       NOT NULL,
    city_name         VARCHAR(100) NOT NULL,
    start_time        TIMESTAMPTZ  NOT NULL,
    end_time          TIMESTAMPTZ  NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    refund_policy_id  BIGINT       NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_show_search ON show.shows (city_id, movie_id, start_time);
CREATE INDEX idx_show_screen_time ON show.shows (screen_id, start_time);

CREATE TABLE show.show_pricing (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id    BIGINT      NOT NULL REFERENCES show.shows (id),
    seat_type  VARCHAR(20) NOT NULL,
    price      BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_show_pricing_type UNIQUE (show_id, seat_type)
);

CREATE TABLE show.show_seats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id     BIGINT      NOT NULL REFERENCES show.shows (id),
    seat_id     BIGINT      NOT NULL,
    row_label   VARCHAR(3)  NOT NULL,
    seat_number INT         NOT NULL,
    seat_type   VARCHAR(20) NOT NULL,
    status      VARCHAR(20) NOT NULL,
    hold_id     BIGINT,
    version     BIGINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_show_seat UNIQUE (show_id, seat_id)
);
CREATE INDEX idx_show_seat_show ON show.show_seats (show_id);
