CREATE SCHEMA IF NOT EXISTS discount;

CREATE TABLE discount.discounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(20) NOT NULL,
    code                VARCHAR(30),
    discount_type       VARCHAR(20) NOT NULL,
    value               BIGINT      NOT NULL,
    max_discount_amount BIGINT,
    min_order_amount    BIGINT      NOT NULL DEFAULT 0,
    valid_from          TIMESTAMPTZ NOT NULL,
    valid_to            TIMESTAMPTZ NOT NULL,
    max_total_uses      INT,
    max_uses_per_user   INT,
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_discount_code UNIQUE (code)
);

CREATE TABLE discount.discount_redemptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_id     BIGINT      NOT NULL REFERENCES discount.discounts (id),
    user_id         BIGINT      NOT NULL,
    booking_id      BIGINT      NOT NULL,
    discount_amount BIGINT      NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_redemption_discount_booking UNIQUE (discount_id, booking_id)
);
CREATE INDEX idx_redemption_discount ON discount.discount_redemptions (discount_id);
CREATE INDEX idx_redemption_discount_user ON discount.discount_redemptions (discount_id, user_id);
