CREATE SCHEMA IF NOT EXISTS booking;

CREATE TABLE booking.seat_holds (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    show_id      BIGINT      NOT NULL,
    status       VARCHAR(20) NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    total_amount BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_seat_hold_sweep ON booking.seat_holds (status, expires_at);

CREATE TABLE booking.bookings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_ref      VARCHAR(12)  NOT NULL,
    user_id          BIGINT       NOT NULL,
    show_id          BIGINT       NOT NULL,
    hold_id          BIGINT       NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    total_amount     BIGINT       NOT NULL,
    discount_id      BIGINT,
    discount_amount  BIGINT       NOT NULL DEFAULT 0,
    payable_amount   BIGINT       NOT NULL,
    movie_title      VARCHAR(200) NOT NULL,
    screen_name      VARCHAR(50)  NOT NULL,
    theatre_name     VARCHAR(150) NOT NULL,
    start_time       TIMESTAMPTZ  NOT NULL,
    refund_policy_id BIGINT       NOT NULL,
    confirmed_at     TIMESTAMPTZ,
    cancelled_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_booking_ref UNIQUE (booking_ref)
);
CREATE INDEX idx_booking_user ON booking.bookings (user_id, id);

CREATE TABLE booking.tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT      NOT NULL REFERENCES booking.bookings (id),
    show_id     BIGINT      NOT NULL,
    seat_id     BIGINT      NOT NULL,
    row_label   VARCHAR(3)  NOT NULL,
    seat_number INT         NOT NULL,
    seat_type   VARCHAR(20) NOT NULL,
    price       BIGINT      NOT NULL,
    status      VARCHAR(20) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_ticket_booking ON booking.tickets (booking_id);
-- Final DB safety net against double-allocation: at most one ACTIVE ticket per (show, seat).
CREATE UNIQUE INDEX uq_ticket_show_seat_active ON booking.tickets (show_id, seat_id) WHERE status = 'ACTIVE';

CREATE TABLE booking.cancellations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id             BIGINT      NOT NULL,
    cancelled_by           BIGINT      NOT NULL,
    reason                 VARCHAR(255),
    refund_percent_applied INT         NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_cancellation_booking UNIQUE (booking_id)
);
