CREATE SCHEMA IF NOT EXISTS payment;

CREATE TABLE payment.payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT      NOT NULL,
    user_id         BIGINT      NOT NULL,
    amount          BIGINT      NOT NULL,
    method          VARCHAR(20) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    txn_ref         VARCHAR(64),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_payment_idempotency UNIQUE (idempotency_key)
);
CREATE INDEX idx_payment_booking ON payment.payments (booking_id);
