CREATE TABLE refund.refunds (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancellation_id BIGINT      NOT NULL,
    payment_id      BIGINT      NOT NULL,
    booking_id      BIGINT      NOT NULL,
    user_id         BIGINT      NOT NULL,
    amount          BIGINT      NOT NULL,
    status          VARCHAR(20) NOT NULL,
    processed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_refund_booking UNIQUE (booking_id)
);
CREATE INDEX idx_refund_user ON refund.refunds (user_id);
